package com.codenjoy.dojo.kata.services;

/*-
 * #%L
 * Codenjoy - it's a dojo-like platform from developers to developers.
 * %%
 * Copyright (C) 2012 - 2022 Codenjoy
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * #L%
 */

import com.codenjoy.dojo.utils.JsonUtils;
import com.codenjoy.dojo.utils.TestUtils;
import com.codenjoy.dojo.utils.smart.SmartAssert;
import org.json.JSONObject;
import org.junit.After;
import org.junit.Test;

import static com.codenjoy.dojo.utils.smart.SmartAssert.assertEquals;
import static java.util.stream.Collectors.toList;

public class GameSettingsTest {

    @After
    public void after() {
        SmartAssert.checkResult();
    }

    @Test
    public void shouldGetAllParameters_withKeys() {
        assertEquals("WIN_SCORE             =[Score] Win score\n" +
                        "LOSE_PENALTY          =[Score] Lose penalty\n" +
                        "A_CONSTANT            =[Score] A constant\n" +
                        "B_CONSTANT            =[Score] B constant\n" +
                        "C_CONSTANT            =[Score] C constant\n" +
                        "D_CONSTANT            =[Score] D constant\n" +
                        "SHOW_DESCRIPTION      =[Game] Show algorithm description in the request\n" +
                        "SHOW_EXPECTED_ANSWER  =[Game] Show expected answer for last question\n" +
                        "SHOW_VALID_IN_HISTORY =[Game] Show expected answer for all history questions",
                TestUtils.toString(new GameSettings().allKeys()));
    }

    @Test
    public void shouldGetAllParameters_alsoWithoutKeys() {
        assertEquals("{\n" +
                        "  '[Game] Show algorithm description in the request':true,\n" +
                        "  '[Game] Show expected answer for all history questions':true,\n" +
                        "  '[Game] Show expected answer for last question':true,\n" +
                        "  '[Level] Map[10]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Divide an integer into multiples of prime numbers:\\\\n1 -> [1]\\\\n2 -> [2]\\\\n3 -> [3]\\\\n4 -> [2,2]\\\\n6 -> [2,3]\\\\n9 -> [3,3]\\\\n12 -> [2,2,3]\\\\n15 -> [3,5]\\\\netc...\\'\\n  ],\\n  \\'name\\':\\'PrimeFactoryAlgorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    if (number == 1) {\\\\n        return \\\\\\\\'[1]\\\\\\\\';\\\\n    }\\\\n    const result = [];\\\\n    for (let i = 2; i <= Math.sqrt(number); i++) {\\\\n        while (number % i === 0) {\\\\n             result.push(i);\\\\n             number /= i;\\\\n        }\\\\n    }\\\\n    if (number > 1) {\\\\n        result.push(number);\\\\n    }\\\\n    return \\\\\\\\'[\\\\\\\\' + result.join(\\\\\\\\',\\\\\\\\') + \\\\\\\\']\\\\\\\\';\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[11]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'2 to the power of 15 = 32768, the sum of digits of the result 3 + 2 + 7 + 6 + 8 = 26. What is the sum of the digits of 2 to the power of i?\\\\nWrite a method for calculation that takes int and returns the result as a String\\'\\n  ],\\n  \\'name\\':\\'PowerDigitSumAlgorithm\\',\\n  \\'winCode\\':\\'function program(power) {\\\\n    const temp = (BigInt(1) << BigInt(power)).toString();\\\\n    let sum = 0;\\\\n    for (let i = 0; i < temp.length; i++) {\\\\n        sum += parseInt(temp[i]);\\\\n    }\\\\n    return sum.toString();\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[12]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'You have bricks of size 5 (bigCount) and 1 (smallCount). Write a method that can determine if a given set of bricks can be used to build a wall of a given length. a given set of bricks to build a wall of a given length (length). For example: \\\\nmethod(3, 1, 8) → true\\\\nmethod(3, 1, 9) → false\\\\nmethod(3, 2, 10) → true\\'\\n  ],\\n  \\'name\\':\\'MakeBricksAlgorithm\\',\\n  \\'winCode\\':\\'function program(input) {\\\\n    const [small, big, goal] = input.split(\\\\\\\\', \\\\\\\\').map(number => parseInt(number));\\\\n    const result = (small >= (goal % 5) && small >= goal - big * 5);\\\\n    return String(result);\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[13]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Write a method that takes one int argument and that returns the factorial of that number as a String.\\\\nWarning: Int/long overflow is possible.\\'\\n  ],\\n  \\'name\\':\\'FactorialAlgorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    const cache = {};\\\\n\\\\n    function calculate(number) {\\\\n        if (number == 0) {\\\\n            return 1n;\\\\n        }\\\\n\\\\n        if (number in cache) {\\\\n            return cache[number];\\\\n        }\\\\n\\\\n        const result = BigInt(number) * calculate(number - 1);\\\\n        cache[number] = result;\\\\n\\\\n        return result;\\\\n    }\\\\n\\\\n    return calculate(number).toString();\\\\n}\\\\n\\'\\n}',\n" +
                        "  '[Level] Map[14]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'For the most of numbers iterative \\\\\\\\'reverse and add\\\\\\\\' actions lead to palindrome number. For example: \\\\nNumber 23: 23 + 32 = 55; \\\\nNumber 254: 254 + 452 = 706; 706 + 607 = 1313; 1313 + 3131 = 4444;\\\\nWrite a method which calculates \\\\\\\\'ReverseAndAdd\\\\\\\\' palindrome for a number. i.e f(23) = 55; f(254) = 4444\\'\\n  ],\\n  \\'name\\':\\'ReverseAddPalindromeAlgorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    let result = BigInt(number);\\\\n    do {\\\\n        result += BigInt(reverse(String(result))); \\\\n    } while (!isPalindrome(result));\\\\n    return String(result);\\\\n}\\\\n\\\\nfunction isPalindrome(input) {\\\\n    let number = String(input);\\\\n    return number === reverse(number);\\\\n}\\\\n\\\\nfunction reverse(string) {\\\\n    return string.split(\\\\\\\\'\\\\\\\\').reverse().join(\\\\\\\\'\\\\\\\\');\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[15]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Continue the sequence 971, 874, 787, 709, 639...\\\\ni.e f(1) = 971, f(2) = 874, ...\\\\nHint: Use subtraction\\'\\n  ],\\n  \\'name\\':\\'Sequence2Algorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    let result = 971;\\\\n\\\\n    for (let i = 1; i < number; i++) {\\\\n        let string = result.toString().padStart(3, \\\\\\\\'0\\\\\\\\');\\\\n        result -= parseInt(string.substring(0, 2));\\\\n    }\\\\n\\\\n    return result.toString();\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[16]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'The first 10 prime numbers are 2, 3, 5, 7, 11, 13, 17, 19, 23, 29. Write a method that returns the i-th prime number.\\'\\n  ],\\n  \\'name\\':\\'XthPrimeAlgorithm\\',\\n  \\'winCode\\':\\'function program(input) {\\\\n    let index = parseInt(input);\\\\n    let count = 0;\\\\n    let result = 2;\\\\n\\\\n    while (count < index) {\\\\n        let isPrime = true;\\\\n        for (let j = 2; j <= Math.sqrt(result); j++) {\\\\n            if (result % j === 0) {\\\\n                isPrime = false;\\\\n                break;\\\\n            }\\\\n        }\\\\n        if (isPrime) {\\\\n            count++;\\\\n            if (count === index) {\\\\n                return result;\\\\n            }\\\\n        }\\\\n        result++;\\\\n    }\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[17]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Write a method that divides two numbers in a column to within 100 digits. If there is a period in the result, it should be written as follows:\\\\n212/133 = 1.(593984962406015037)\\\\n87/78 = 1.1(153846)\\'\\n  ],\\n  \\'name\\':\\'LongDivisionAlgorithm\\',\\n  \\'winCode\\':\\'function program(input) {\\\\n    let a = Number(input.split(\\\\\\\\',\\\\\\\\')[0]);\\\\n    let b = Number(input.split(\\\\\\\\',\\\\\\\\')[1]);\\\\n\\\\n    if (b === 0) {\\\\n        return \\\\\\\\'Div by zero error!\\\\\\\\';\\\\n    }\\\\n    if (a === 0) {\\\\n        return \\\\\\\\'0\\\\\\\\';\\\\n    }\\\\n    const isMinus = (a < 0 && b > 0 || a > 0 && b < 0);\\\\n    a = Math.abs(a);\\\\n    b = Math.abs(b);\\\\n\\\\n    const length = 100;\\\\n    const DOT = -1;\\\\n    const TEN = 10;\\\\n    const NOT_FOUND = -1;\\\\n\\\\n    const result = [];\\\\n\\\\n    const aa = new Array(length * 2).fill(0);\\\\n    let ia = 0;\\\\n    let ceilpos = 0;\\\\n\\\\n    let isCalcCeil = a >= b;\\\\n    if (!isCalcCeil) {\\\\n        result.push(\\\\\\\\'0\\\\\\\\', \\\\\\\\'.\\\\\\\\');\\\\n        aa[ia++] = 0;\\\\n        aa[ia++] = DOT;\\\\n        ceilpos = ia - 1;\\\\n    }\\\\n\\\\n    while (a != 0 && (result.length - ceilpos) <= length) {\\\\n        if (a < b) {\\\\n            if (isCalcCeil) {\\\\n                result.push(\\\\\\\\'.\\\\\\\\');\\\\n                aa[ia++] = DOT;\\\\n                ceilpos = ia - 1;\\\\n                isCalcCeil = false;\\\\n            }\\\\n            a *= TEN;\\\\n        }\\\\n        while (a < b) {\\\\n            result.push(\\\\\\\\'0\\\\\\\\');\\\\n            aa[ia++] = 0;\\\\n            a *= TEN;\\\\n        }\\\\n\\\\n        let found = NOT_FOUND;\\\\n        for (let ja = 0; ja < ia; ja++) {\\\\n            if (aa[ja] === a) {\\\\n                found = ja;\\\\n                break;\\\\n            }\\\\n        }\\\\n        if (found !== NOT_FOUND) {\\\\n            result.splice(found, 0, \\\\\\\\'(\\\\\\\\');\\\\n            result.push(\\\\\\\\')\\\\\\\\');\\\\n            break;\\\\n        }\\\\n\\\\n        const c = Math.floor(a / b);\\\\n        if (isCalcCeil) {\\\\n            let c1 = c;\\\\n            while (c1 / TEN > 10000000) {\\\\n                aa[ia++] = c1 % TEN;\\\\n                c1 = Math.floor(c1 / TEN);\\\\n            }\\\\n            aa[ia++] = c1;\\\\n        } else {\\\\n            aa[ia++] = a;\\\\n        }\\\\n        const d = a % b;\\\\n        result.push(c);\\\\n        a = d;\\\\n\\\\n    }\\\\n\\\\n    return ((isMinus) ? \\\\\\\\'-\\\\\\\\' : \\\\\\\\'\\\\\\\\') + result.join(\\\\\\\\'\\\\\\\\');\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[18]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'No more Levels. You win!\\'\\n  ],\\n  \\'name\\':\\'NullLevel\\',\\n  \\'winCode\\':\\'function program(question) {\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[1]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Write a method that takes a single string argument and return the string \\\\\\\\'world\\\\\\\\' if \\\\\\\\'hello\\\\\\\\' came in.\\',\\n    \\'Please write js method.\\',\\n    \\'Now please improve the algorithm so that it returns\\\\\\\\'hello\\\\\\\\' if \\\\\\\\'world\\\\\\\\' came in. Previous logic should work also\\',\\n    \\'One more improvement: in other cases the algorithm should return the same string that came in.\\'\\n  ],\\n  \\'name\\':\\'HelloWorldAlgorithm\\',\\n  \\'winCode\\':\\'function program(question) {\\\\n    if (question == \\\\\\\\'hello\\\\\\\\'){\\\\n        return \\\\\\\\'world\\\\\\\\';\\\\n    }\\\\n    if (question == \\\\\\\\'world\\\\\\\\'){\\\\n        return \\\\\\\\'hello\\\\\\\\';\\\\n    }\\\\n    return question;\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[2]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Write a javascript method that takes one int argument and returns a string containing the number itself.\\',\\n    \\'For those numbers that are divisible by 3, the method should return \\\\\\\\'Fizz\\\\\\\\'\\',\\n    \\'For those numbers divisible by 5 it should return \\\\\\\\'Buzz\\\\\\\\'.\\',\\n    \\'For those numbers divisible by both 3 and 5 - \\\\\\\\'FizzBuzz\\\\\\\\'.\\',\\n    \\'Proceed in the same way if there is a number with a divisor of 7. The word \\\\\\\\'Muzz\\\\\\\\' is used for it. .\\',\\n    \\'Please write optimized code without any duplication.\\',\\n    \\'For divider 11 - the word must be \\\\\\\\'Duzz\\\\\\\\'.\\',\\n    \\'For divider 13 - the word must be \\\\\\\\'Cazz\\\\\\\\'.\\'\\n  ],\\n  \\'name\\':\\'FizzBuzzAlgorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    const divisors = [3, 5, 7, 11, 13];\\\\n    const strings = [\\\\\\\\'Fizz\\\\\\\\', \\\\\\\\'Buzz\\\\\\\\', \\\\\\\\'Muzz\\\\\\\\', \\\\\\\\'Duzz\\\\\\\\', \\\\\\\\'Cazz\\\\\\\\'];\\\\n    let str = \\\\\\\\'\\\\\\\\';\\\\n    for (let i = 0; i < divisors.length; i++) {\\\\n        if (number % divisors[i] === 0) {\\\\n            str += strings[i];\\\\n        }\\\\n    }\\\\n    return str || number.toString();\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[3]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Write a javascript method that takes one int argument and returns a string based on fizzBuzz algorithm:\\\\n1=>15:3*5:FizzBuzz\\\\n2=>21:3*7:FizzMuzz\\\\n3=>33:3*11:FizzDuzz\\\\n4=>35:5*7:BuzzMuzz\\\\n25=>none\\'\\n  ],\\n  \\'name\\':\\'FizzBuzzMultiplierAlgorithm\\',\\n  \\'winCode\\':\\'function program(index) {\\\\n    if (index <= 0 || index >= 25) {\\\\n        return \\\\\\\\'none\\\\\\\\';\\\\n    }\\\\n    \\\\n    const PRIMES = [3, 5, 7, 11, 13];\\\\n    \\\\n    let number = 0;\\\\n    let found = 0;\\\\n    \\\\n    const divisors = [];\\\\n    \\\\n    while (found != index) {\\\\n        number++;\\\\n        let rest = number;\\\\n        divisors.length = 0;\\\\n        \\\\n        for (let i = 0; i < PRIMES.length && rest > 1; i++) {\\\\n            if (rest <= PRIMES[i]) {\\\\n                break;\\\\n            }\\\\n            if (number % PRIMES[i] === 0) {\\\\n                divisors.push(PRIMES[i]);\\\\n                rest /= PRIMES[i];\\\\n            }\\\\n        }\\\\n        \\\\n        if (divisors.length > 1 && rest === 1) {\\\\n            found++;\\\\n        }\\\\n    }\\\\n    \\\\n    const divisorsStr = divisors.join(\\\\\\'*\\\\\\');\\\\n    return `${number}:${divisorsStr}:${fizzBuzz(number)}`;\\\\n}\\\\nfunction program(number) {\\\\n    const divisors = [3, 5, 7, 11, 13];\\\\n    const strings = [\\\\\\\\'Fizz\\\\\\\\', \\\\\\\\'Buzz\\\\\\\\', \\\\\\\\'Muzz\\\\\\\\', \\\\\\\\'Duzz\\\\\\\\', \\\\\\\\'Cazz\\\\\\\\'];\\\\n    let str = \\\\\\\\'\\\\\\\\';\\\\n    for (let i = 0; i < divisors.length; i++) {\\\\n        if (number % divisors[i] === 0) {\\\\n            str += strings[i];\\\\n        }\\\\n    }\\\\n    return str || number.toString();\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[4]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'The sum of the squares of the first ten positive integers \\\\n1^2 + 2^2 + ... + 10^2 = 385. \\\\nAnd the square of the sum is \\\\n(1 + 2 + ... + 10)^2 = 55^2 = 3025. \\\\nTherefore, the difference between the sum of the squares and the square of the sum of the first ten natural numbers is equal to 3025 - 385 = 2640. \\\\nCreate a method that calculates the difference between the sum squares and the square of the sum for the natural number i.\\'\\n  ],\\n  \\'name\\':\\'SumSquareDifferenceAlgorithm\\',\\n  \\'winCode\\':\\'function program(question) {\\\\n    let number = parseInt(question);\\\\n    let sumOfSquares = (number * (number + 1) * (2 * number + 1)) / 6;\\\\n    let squareOfSum = Math.pow((number * (number + 1)) / 2, 2);\\\\n    return squareOfSum - sumOfSquares;\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[5]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Given the sequence: 1, 0, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12, 15, 14...\\\\nThe sequence starts with element number 0: f(0)=1.\\\\nYour task is to write a function that returns the element at index n: f(n)=?\\'\\n  ],\\n  \\'name\\':\\'SimpleMathAlgorithm\\',\\n  \\'winCode\\':\\'function get(input) {\\\\n    let number = parseInt(input);\\\\n    return (number % 2 == 0)\\\\n        ? number + 1\\\\n        : number - 1;\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[6]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'The order matters...\\\\n Everything is quite simple. \\\\nIn a string of three characters, the last character becomes the first one,\\\\n and the first two characters shift one position to the right. \\\\nFor example: abc=>cab...\\'\\n  ],\\n  \\'name\\':\\'CharOrderAlgorithm\\',\\n  \\'winCode\\':\\'function program(input) {\\\\n    return input.substring(2)\\\\n        + input.substring(0, 2);\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[7]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Order matters...\\\\nYou need to work with three-digit numbers. \\\\nSolve the algorithm for changing the number according to the given examples: \\\\nExamples: 111=>222, 123=>423, 679=>078, 999=>000, 012=>312, 090=>110, 444=>555, 090=>110, 916=>702\\'\\n  ],\\n  \\'name\\':\\'NumberOrderAlgorithm\\',\\n  \\'winCode\\':\\'function program(input) {\\\\n    return \\\\\\\\'\\\\\\\\' + getNextNumber(input.charAt(2))\\\\n        + getNextNumber(input.charAt(0))\\\\n        + getNextNumber(input.charAt(1));\\\\n}\\\\n\\\\nfunction getNextNumber(number) {\\\\n    return (parseInt(number) + 1) % 10;\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[8]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Continue the sequence 101, 112, 131, 415, 161, 718... \\\\ni.e f(1) = 101, f(2) = 112, ...\\\\nHint: Look at the whole picture\\'\\n  ],\\n  \\'name\\':\\'Sequence1Algorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    const START_WITH = 10;\\\\n    const GROUP = 3;\\\\n    const MAX = number * GROUP;\\\\n    let i = 0;\\\\n    let buffer = \\\\\\'\\\\\\';\\\\n    while (buffer.length < MAX) {\\\\n        buffer += START_WITH + i;\\\\n        i++;\\\\n    }\\\\n    return buffer.substring(MAX - GROUP, MAX);\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[9]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Make a method that returns a Fibonacci number from the series by its number:\\\\nf(0) = 0\\\\nf(1) = 1\\\\nf(2) = 0 + 1 = 1\\\\nf(3) = 1 + 1 = 2\\\\nf(4) = 1 + 2 = 3\\\\nf(5) = 2 + 3 = 5\\\\nf(6) = 3 + 5 = 8\\\\nf(7) = 5 + 8 = 13\\\\nf(8) = 8 + 13 = 21\\\\nf(9) = 13 + 21 = 34\\\\netc...\\'\\n  ],\\n  \\'name\\':\\'FibonacciNumbersAlgorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    let previous = 0, current = 1;\\\\n    for (let i = 0; i < number; i++) {\\\\n         [previous, current] = [current, previous + current];\\\\n    }\\\\n    return String(previous);\\\\n}\\'\\n}',\n" +
                        "  '[Score] A constant':100,\n" +
                        "  '[Score] B constant':3,\n" +
                        "  '[Score] C constant':30,\n" +
                        "  '[Score] D constant':10,\n" +
                        "  '[Score] Lose penalty':-100,\n" +
                        "  '[Score] Win score':30\n" +
                        "}",
                JsonUtils.prettyPrint(new GameSettings().asNameValueJson()));
    }

    @Test
    public void shouldGetAllSortedLevels() {
        assertEquals("{\n" +
                        "  '[Game] Show algorithm description in the request':true,\n" +
                        "  '[Game] Show expected answer for all history questions':true,\n" +
                        "  '[Game] Show expected answer for last question':true,\n" +
                        "  '[Level] Map[10]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Divide an integer into multiples of prime numbers:\\\\n1 -> [1]\\\\n2 -> [2]\\\\n3 -> [3]\\\\n4 -> [2,2]\\\\n6 -> [2,3]\\\\n9 -> [3,3]\\\\n12 -> [2,2,3]\\\\n15 -> [3,5]\\\\netc...\\'\\n  ],\\n  \\'name\\':\\'PrimeFactoryAlgorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    if (number == 1) {\\\\n        return \\\\\\\\'[1]\\\\\\\\';\\\\n    }\\\\n    const result = [];\\\\n    for (let i = 2; i <= Math.sqrt(number); i++) {\\\\n        while (number % i === 0) {\\\\n             result.push(i);\\\\n             number /= i;\\\\n        }\\\\n    }\\\\n    if (number > 1) {\\\\n        result.push(number);\\\\n    }\\\\n    return \\\\\\\\'[\\\\\\\\' + result.join(\\\\\\\\',\\\\\\\\') + \\\\\\\\']\\\\\\\\';\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[11]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'2 to the power of 15 = 32768, the sum of digits of the result 3 + 2 + 7 + 6 + 8 = 26. What is the sum of the digits of 2 to the power of i?\\\\nWrite a method for calculation that takes int and returns the result as a String\\'\\n  ],\\n  \\'name\\':\\'PowerDigitSumAlgorithm\\',\\n  \\'winCode\\':\\'function program(power) {\\\\n    const temp = (BigInt(1) << BigInt(power)).toString();\\\\n    let sum = 0;\\\\n    for (let i = 0; i < temp.length; i++) {\\\\n        sum += parseInt(temp[i]);\\\\n    }\\\\n    return sum.toString();\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[12]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'You have bricks of size 5 (bigCount) and 1 (smallCount). Write a method that can determine if a given set of bricks can be used to build a wall of a given length. a given set of bricks to build a wall of a given length (length). For example: \\\\nmethod(3, 1, 8) → true\\\\nmethod(3, 1, 9) → false\\\\nmethod(3, 2, 10) → true\\'\\n  ],\\n  \\'name\\':\\'MakeBricksAlgorithm\\',\\n  \\'winCode\\':\\'function program(input) {\\\\n    const [small, big, goal] = input.split(\\\\\\\\', \\\\\\\\').map(number => parseInt(number));\\\\n    const result = (small >= (goal % 5) && small >= goal - big * 5);\\\\n    return String(result);\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[13]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Write a method that takes one int argument and that returns the factorial of that number as a String.\\\\nWarning: Int/long overflow is possible.\\'\\n  ],\\n  \\'name\\':\\'FactorialAlgorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    const cache = {};\\\\n\\\\n    function calculate(number) {\\\\n        if (number == 0) {\\\\n            return 1n;\\\\n        }\\\\n\\\\n        if (number in cache) {\\\\n            return cache[number];\\\\n        }\\\\n\\\\n        const result = BigInt(number) * calculate(number - 1);\\\\n        cache[number] = result;\\\\n\\\\n        return result;\\\\n    }\\\\n\\\\n    return calculate(number).toString();\\\\n}\\\\n\\'\\n}',\n" +
                        "  '[Level] Map[14]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'For the most of numbers iterative \\\\\\\\'reverse and add\\\\\\\\' actions lead to palindrome number. For example: \\\\nNumber 23: 23 + 32 = 55; \\\\nNumber 254: 254 + 452 = 706; 706 + 607 = 1313; 1313 + 3131 = 4444;\\\\nWrite a method which calculates \\\\\\\\'ReverseAndAdd\\\\\\\\' palindrome for a number. i.e f(23) = 55; f(254) = 4444\\'\\n  ],\\n  \\'name\\':\\'ReverseAddPalindromeAlgorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    let result = BigInt(number);\\\\n    do {\\\\n        result += BigInt(reverse(String(result))); \\\\n    } while (!isPalindrome(result));\\\\n    return String(result);\\\\n}\\\\n\\\\nfunction isPalindrome(input) {\\\\n    let number = String(input);\\\\n    return number === reverse(number);\\\\n}\\\\n\\\\nfunction reverse(string) {\\\\n    return string.split(\\\\\\\\'\\\\\\\\').reverse().join(\\\\\\\\'\\\\\\\\');\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[15]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Continue the sequence 971, 874, 787, 709, 639...\\\\ni.e f(1) = 971, f(2) = 874, ...\\\\nHint: Use subtraction\\'\\n  ],\\n  \\'name\\':\\'Sequence2Algorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    let result = 971;\\\\n\\\\n    for (let i = 1; i < number; i++) {\\\\n        let string = result.toString().padStart(3, \\\\\\\\'0\\\\\\\\');\\\\n        result -= parseInt(string.substring(0, 2));\\\\n    }\\\\n\\\\n    return result.toString();\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[16]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'The first 10 prime numbers are 2, 3, 5, 7, 11, 13, 17, 19, 23, 29. Write a method that returns the i-th prime number.\\'\\n  ],\\n  \\'name\\':\\'XthPrimeAlgorithm\\',\\n  \\'winCode\\':\\'function program(input) {\\\\n    let index = parseInt(input);\\\\n    let count = 0;\\\\n    let result = 2;\\\\n\\\\n    while (count < index) {\\\\n        let isPrime = true;\\\\n        for (let j = 2; j <= Math.sqrt(result); j++) {\\\\n            if (result % j === 0) {\\\\n                isPrime = false;\\\\n                break;\\\\n            }\\\\n        }\\\\n        if (isPrime) {\\\\n            count++;\\\\n            if (count === index) {\\\\n                return result;\\\\n            }\\\\n        }\\\\n        result++;\\\\n    }\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[17]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Write a method that divides two numbers in a column to within 100 digits. If there is a period in the result, it should be written as follows:\\\\n212/133 = 1.(593984962406015037)\\\\n87/78 = 1.1(153846)\\'\\n  ],\\n  \\'name\\':\\'LongDivisionAlgorithm\\',\\n  \\'winCode\\':\\'function program(input) {\\\\n    let a = Number(input.split(\\\\\\\\',\\\\\\\\')[0]);\\\\n    let b = Number(input.split(\\\\\\\\',\\\\\\\\')[1]);\\\\n\\\\n    if (b === 0) {\\\\n        return \\\\\\\\'Div by zero error!\\\\\\\\';\\\\n    }\\\\n    if (a === 0) {\\\\n        return \\\\\\\\'0\\\\\\\\';\\\\n    }\\\\n    const isMinus = (a < 0 && b > 0 || a > 0 && b < 0);\\\\n    a = Math.abs(a);\\\\n    b = Math.abs(b);\\\\n\\\\n    const length = 100;\\\\n    const DOT = -1;\\\\n    const TEN = 10;\\\\n    const NOT_FOUND = -1;\\\\n\\\\n    const result = [];\\\\n\\\\n    const aa = new Array(length * 2).fill(0);\\\\n    let ia = 0;\\\\n    let ceilpos = 0;\\\\n\\\\n    let isCalcCeil = a >= b;\\\\n    if (!isCalcCeil) {\\\\n        result.push(\\\\\\\\'0\\\\\\\\', \\\\\\\\'.\\\\\\\\');\\\\n        aa[ia++] = 0;\\\\n        aa[ia++] = DOT;\\\\n        ceilpos = ia - 1;\\\\n    }\\\\n\\\\n    while (a != 0 && (result.length - ceilpos) <= length) {\\\\n        if (a < b) {\\\\n            if (isCalcCeil) {\\\\n                result.push(\\\\\\\\'.\\\\\\\\');\\\\n                aa[ia++] = DOT;\\\\n                ceilpos = ia - 1;\\\\n                isCalcCeil = false;\\\\n            }\\\\n            a *= TEN;\\\\n        }\\\\n        while (a < b) {\\\\n            result.push(\\\\\\\\'0\\\\\\\\');\\\\n            aa[ia++] = 0;\\\\n            a *= TEN;\\\\n        }\\\\n\\\\n        let found = NOT_FOUND;\\\\n        for (let ja = 0; ja < ia; ja++) {\\\\n            if (aa[ja] === a) {\\\\n                found = ja;\\\\n                break;\\\\n            }\\\\n        }\\\\n        if (found !== NOT_FOUND) {\\\\n            result.splice(found, 0, \\\\\\\\'(\\\\\\\\');\\\\n            result.push(\\\\\\\\')\\\\\\\\');\\\\n            break;\\\\n        }\\\\n\\\\n        const c = Math.floor(a / b);\\\\n        if (isCalcCeil) {\\\\n            let c1 = c;\\\\n            while (c1 / TEN > 10000000) {\\\\n                aa[ia++] = c1 % TEN;\\\\n                c1 = Math.floor(c1 / TEN);\\\\n            }\\\\n            aa[ia++] = c1;\\\\n        } else {\\\\n            aa[ia++] = a;\\\\n        }\\\\n        const d = a % b;\\\\n        result.push(c);\\\\n        a = d;\\\\n\\\\n    }\\\\n\\\\n    return ((isMinus) ? \\\\\\\\'-\\\\\\\\' : \\\\\\\\'\\\\\\\\') + result.join(\\\\\\\\'\\\\\\\\');\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[18]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'No more Levels. You win!\\'\\n  ],\\n  \\'name\\':\\'NullLevel\\',\\n  \\'winCode\\':\\'function program(question) {\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[1]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Write a method that takes a single string argument and return the string \\\\\\\\'world\\\\\\\\' if \\\\\\\\'hello\\\\\\\\' came in.\\',\\n    \\'Please write js method.\\',\\n    \\'Now please improve the algorithm so that it returns\\\\\\\\'hello\\\\\\\\' if \\\\\\\\'world\\\\\\\\' came in. Previous logic should work also\\',\\n    \\'One more improvement: in other cases the algorithm should return the same string that came in.\\'\\n  ],\\n  \\'name\\':\\'HelloWorldAlgorithm\\',\\n  \\'winCode\\':\\'function program(question) {\\\\n    if (question == \\\\\\\\'hello\\\\\\\\'){\\\\n        return \\\\\\\\'world\\\\\\\\';\\\\n    }\\\\n    if (question == \\\\\\\\'world\\\\\\\\'){\\\\n        return \\\\\\\\'hello\\\\\\\\';\\\\n    }\\\\n    return question;\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[2]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Write a javascript method that takes one int argument and returns a string containing the number itself.\\',\\n    \\'For those numbers that are divisible by 3, the method should return \\\\\\\\'Fizz\\\\\\\\'\\',\\n    \\'For those numbers divisible by 5 it should return \\\\\\\\'Buzz\\\\\\\\'.\\',\\n    \\'For those numbers divisible by both 3 and 5 - \\\\\\\\'FizzBuzz\\\\\\\\'.\\',\\n    \\'Proceed in the same way if there is a number with a divisor of 7. The word \\\\\\\\'Muzz\\\\\\\\' is used for it. .\\',\\n    \\'Please write optimized code without any duplication.\\',\\n    \\'For divider 11 - the word must be \\\\\\\\'Duzz\\\\\\\\'.\\',\\n    \\'For divider 13 - the word must be \\\\\\\\'Cazz\\\\\\\\'.\\'\\n  ],\\n  \\'name\\':\\'FizzBuzzAlgorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    const divisors = [3, 5, 7, 11, 13];\\\\n    const strings = [\\\\\\\\'Fizz\\\\\\\\', \\\\\\\\'Buzz\\\\\\\\', \\\\\\\\'Muzz\\\\\\\\', \\\\\\\\'Duzz\\\\\\\\', \\\\\\\\'Cazz\\\\\\\\'];\\\\n    let str = \\\\\\\\'\\\\\\\\';\\\\n    for (let i = 0; i < divisors.length; i++) {\\\\n        if (number % divisors[i] === 0) {\\\\n            str += strings[i];\\\\n        }\\\\n    }\\\\n    return str || number.toString();\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[3]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Write a js function that takes an integer index as input and returns a string in the format \\\\\\\\'number:divisors:fizzBuzz\\\\\\\\', where \\\\\\\\'number\\\\\\\\' is the nth positive integer that has at least two distinct dividers [3, 5, 7, 9, 13] and is divisible by them without a rest, \\\\\\\\'divisors\\\\\\\\' is a separated by \\\\\\\\'*\\\\\\\\' list of the distinct prime factors of \\\\\\\\'number\\\\\\\\', and \\\\\\\\'fizzBuzz\\\\\\\\' is the result of calling a function \\\\\\\\'fizzBuzz(number)\\\\\\\\'. If the input index is less than or equal to 0 or greater than or equal to 25, return \\\\\\\\'none\\\\\\\\'.\\',\\n    \\'For example:\\\\n1=>15:3*5:FizzBuzz\\\\n2=>21:3*7:FizzMuzz\\\\n3=>33:3*11:FizzDuzz\\\\n10=>105:3*5*7:FizzBuzzMuzz\\\\n12=>165:3*5*11:FizzBuzzDuzz\\\\n13=>195:3*5*13:FizzBuzzCazz\\\\n21=>1155:3*5*7*11:FizzBuzzMuzzDuzz\\\\n23=>2145:3*5*11*13:FizzBuzzDuzzCazz\\\\n24=>3003:3*7*11*13:FizzMuzzDuzzCazz\\\\n26=>15015:3*5*7*11*13:FizzBuzzMuzzDuzzCazz\\'\\n  ],\\n  \\'name\\':\\'FizzBuzzMultiplierAlgorithm\\',\\n  \\'winCode\\':\\'function program(index) {\\\\n    if (index < 1 || index > 26) {\\\\n        return \\\\\\\\'none\\\\\\\\';\\\\n    }\\\\n    \\\\n    const PRIMES = [3, 5, 7, 11, 13];\\\\n    \\\\n    let number = 0;\\\\n    let found = 0;\\\\n    \\\\n    const divisors = [];\\\\n    \\\\n    while (found != index) {\\\\n        number++;\\\\n        let rest = number;\\\\n        divisors.length = 0;\\\\n        \\\\n        for (let i = 0; i < PRIMES.length && rest > 1; i++) {\\\\n            if (rest <= PRIMES[i]) {\\\\n                break;\\\\n            }\\\\n            if (number % PRIMES[i] === 0) {\\\\n                divisors.push(PRIMES[i]);\\\\n                rest /= PRIMES[i];\\\\n            }\\\\n        }\\\\n        \\\\n        if (divisors.length > 1 && rest === 1) {\\\\n            found++;\\\\n        }\\\\n    }\\\\n    \\\\n    const divisorsStr = divisors.join(\\\\\\'*\\\\\\');\\\\n    return `${number}:${divisorsStr}:${fizzBuzz(number)}`;\\\\n}\\\\nfunction program(number) {\\\\n    const divisors = [3, 5, 7, 11, 13];\\\\n    const strings = [\\\\\\\\'Fizz\\\\\\\\', \\\\\\\\'Buzz\\\\\\\\', \\\\\\\\'Muzz\\\\\\\\', \\\\\\\\'Duzz\\\\\\\\', \\\\\\\\'Cazz\\\\\\\\'];\\\\n    let str = \\\\\\\\'\\\\\\\\';\\\\n    for (let i = 0; i < divisors.length; i++) {\\\\n        if (number % divisors[i] === 0) {\\\\n            str += strings[i];\\\\n        }\\\\n    }\\\\n    return str || number.toString();\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[4]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'The sum of the squares of the first ten positive integers \\\\n1^2 + 2^2 + ... + 10^2 = 385. \\\\nAnd the square of the sum is \\\\n(1 + 2 + ... + 10)^2 = 55^2 = 3025. \\\\nTherefore, the difference between the sum of the squares and the square of the sum of the first ten natural numbers is equal to 3025 - 385 = 2640. \\\\nCreate a method that calculates the difference between the sum squares and the square of the sum for the natural number i.\\'\\n  ],\\n  \\'name\\':\\'SumSquareDifferenceAlgorithm\\',\\n  \\'winCode\\':\\'function program(question) {\\\\n    let number = parseInt(question);\\\\n    let sumOfSquares = (number * (number + 1) * (2 * number + 1)) / 6;\\\\n    let squareOfSum = Math.pow((number * (number + 1)) / 2, 2);\\\\n    return squareOfSum - sumOfSquares;\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[5]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Given the sequence: 1, 0, 3, 2, 5, 4, 7, 6, 9, 8, 11, 10, 13, 12, 15, 14...\\\\nThe sequence starts with element number 0: f(0)=1.\\\\nYour task is to write a function that returns the element at index n: f(n)=?\\'\\n  ],\\n  \\'name\\':\\'SimpleMathAlgorithm\\',\\n  \\'winCode\\':\\'function get(input) {\\\\n    let number = parseInt(input);\\\\n    return (number % 2 == 0)\\\\n        ? number + 1\\\\n        : number - 1;\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[6]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'The order matters...\\\\n Everything is quite simple. \\\\nIn a string of three characters, the last character becomes the first one,\\\\n and the first two characters shift one position to the right. \\\\nFor example: abc=>cab...\\'\\n  ],\\n  \\'name\\':\\'CharOrderAlgorithm\\',\\n  \\'winCode\\':\\'function program(input) {\\\\n    return input.substring(2)\\\\n        + input.substring(0, 2);\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[7]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Order matters...\\\\nYou need to work with three-digit numbers. \\\\nSolve the algorithm for changing the number according to the given examples: \\\\nExamples: 111=>222, 123=>423, 679=>078, 999=>000, 012=>312, 090=>110, 444=>555, 090=>110, 916=>702\\'\\n  ],\\n  \\'name\\':\\'NumberOrderAlgorithm\\',\\n  \\'winCode\\':\\'function program(input) {\\\\n    return \\\\\\\\'\\\\\\\\' + getNextNumber(input.charAt(2))\\\\n        + getNextNumber(input.charAt(0))\\\\n        + getNextNumber(input.charAt(1));\\\\n}\\\\n\\\\nfunction getNextNumber(number) {\\\\n    return (parseInt(number) + 1) % 10;\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[8]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Continue the sequence 101, 112, 131, 415, 161, 718... \\\\ni.e f(1) = 101, f(2) = 112, ...\\\\nHint: Look at the whole picture\\'\\n  ],\\n  \\'name\\':\\'Sequence1Algorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    const START_WITH = 10;\\\\n    const GROUP = 3;\\\\n    const MAX = number * GROUP;\\\\n    let i = 0;\\\\n    let buffer = \\\\\\'\\\\\\';\\\\n    while (buffer.length < MAX) {\\\\n        buffer += START_WITH + i;\\\\n        i++;\\\\n    }\\\\n    return buffer.substring(MAX - GROUP, MAX);\\\\n}\\'\\n}',\n" +
                        "  '[Level] Map[9]':'{\\n  \\'defaultCode\\':\\'function program(question) {\\\\n    // TODO implement your logic here\\\\n    return \\\\\\\\'answer\\\\\\\\';\\\\n}\\',\\n  \\'help\\':[\\n    \\'Make a method that returns a Fibonacci number from the series by its number:\\\\nf(0) = 0\\\\nf(1) = 1\\\\nf(2) = 0 + 1 = 1\\\\nf(3) = 1 + 1 = 2\\\\nf(4) = 1 + 2 = 3\\\\nf(5) = 2 + 3 = 5\\\\nf(6) = 3 + 5 = 8\\\\nf(7) = 5 + 8 = 13\\\\nf(8) = 8 + 13 = 21\\\\nf(9) = 13 + 21 = 34\\\\netc...\\'\\n  ],\\n  \\'name\\':\\'FibonacciNumbersAlgorithm\\',\\n  \\'winCode\\':\\'function program(number) {\\\\n    let previous = 0, current = 1;\\\\n    for (let i = 0; i < number; i++) {\\\\n         [previous, current] = [current, previous + current];\\\\n    }\\\\n    return String(previous);\\\\n}\\'\\n}',\n" +
                        "  '[Score] A constant':100,\n" +
                        "  '[Score] B constant':3,\n" +
                        "  '[Score] C constant':30,\n" +
                        "  '[Score] D constant':10,\n" +
                        "  '[Score] Lose penalty':-100,\n" +
                        "  '[Score] Win score':30\n" +
                        "}",
                JsonUtils.prettyPrint(
                        new GameSettings().levels().stream()
                                .map(level -> new JSONObject(){{
                                    put("name", level.name());
                                    put("description", level.description());
                                    put("complexity", level.complexity());
                                    put("size", level.size());
                                    put("qa", level.getQuestionAnswers());
                                }})
                                .collect(toList())
                ));
    }
}